In [1]:
import numpy as np

# Creating Array

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [3]:
# Some attributes 
# Dimension
print(arr.ndim)
#shape
print(arr.shape)
#size
print(arr.size)
#type
print(arr.dtype)
#item size
print(arr.itemsize)

1
(25,)
25
int32
4


In [18]:
# copy
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
print(z)

[1 2 3]


In [19]:
# empty
np.empty([2, 2])

array([[2.33643959e-307, 2.44771536e-307],
       [3.44900369e-307, 4.22792214e-307]])

In [22]:
# empty_like 
a = ([1,2,3], [4,5,6]) 
np.empty_like(a)

array([[         0,          0,          0],
       [1072693248, 1719614413, 1073127582]])

In [23]:
#eye
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [24]:
#fromfunction
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
# identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# linspace
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [28]:
#logspace
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [29]:
#mgrid
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

# Functions

In [4]:
# creating array of zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# creating array of ones 
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# arange function 
np.arange( 10, 30, 5) 

array([10, 15, 20, 25])

In [7]:
#universal functions
B = np.arange(3)
B

array([0, 1, 2])

In [8]:
print(np.exp(B))
print(np.sqrt(B))

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [9]:
# convering 1D array in to 2D array 
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
# getting common item between 2 arrays
a = np.array([1,2,3,4,5])
b = np.array([3,5,8,9,2])
np.intersect1d(a,b)

array([2, 3, 5])

In [11]:
# removing those items from 1sr array that exists in 2nd array
a = np.array([1,2,3,4,5])
b = np.array([3,5,8,9,2])
np.setdiff1d(a,b)

array([1, 4])

In [12]:
# swap two cols in 2D array
d = np.arange(25).reshape(5,5)
d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
d[:, [1,0,2]]

array([[ 1,  0,  2],
       [ 6,  5,  7],
       [11, 10, 12],
       [16, 15, 17],
       [21, 20, 22]])

In [14]:
# swap 2 rows in 2D array
e = np.arange(25).reshape(5,5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
e[[1,0,2],:]

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [16]:
# limiting the umber  of items showing 
np.set_printoptions(threshold=6)
e = np.arange(25)
e

array([ 0,  1,  2, ..., 22, 23, 24])

In [2]:
#split 
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [3]:
#stack 
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [4]:
# concatinate 
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [8]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [9]:
# digonal
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [10]:
a.diagonal()

array([0, 3])

In [11]:
a.diagonal(1)

array([1])

In [12]:
#split
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [13]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [14]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]),
 array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]),
 array([], shape=(2, 2, 0), dtype=float64)]

In [15]:
# dstack
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [16]:
# hsplit
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [17]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [18]:
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [19]:
#hstack
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [20]:
#ravel
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [21]:
#repeat
np.repeat(3, 4)

array([3, 3, 3, 3])

In [24]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [25]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [27]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [28]:
#squeeze
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [29]:
np.squeeze(x).shape

(3,)

In [30]:
np.squeeze(x, axis=0).shape

(3, 1)

In [31]:
#take
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)

array([4, 3, 6])

In [32]:
#transpose
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [33]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [34]:
#vsplit
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [35]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [36]:
#vstack
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
#all
np.all([[True,False],[True,True]])

False

In [38]:
np.all([-1, 4, 5])

True

In [39]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#where
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [41]:
#sort
a = np.array([[1,4],[3,1]])
np.sort(a)

array([[1, 4],
       [1, 3]])

In [42]:
np.sort(a, axis=None)

array([1, 1, 3, 4])

In [43]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [44]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.compress([0, 1], a, axis=0)

array([[3, 4]])

In [46]:
#cumprod
a = np.array([1,2,3])
np.cumprod(a)

array([1, 2, 6], dtype=int32)

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(a, dtype=float)

array([  1.,   2.,   6.,  24., 120., 720.])

In [48]:
#cumsum
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [50]:
#inner
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [52]:
#fill
a = np.array([1, 2])
a.fill(0)
a

array([0, 0])

In [53]:
#put mask 
x = np.arange(6).reshape(2, 3)
np.putmask(x, x>2, x**2)
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [54]:
x = np.arange(5)
np.putmask(x, x>1, [-33, -44])
x

array([  0,   1, -33, -44, -33])

In [55]:
#real
a = np.array([1+2j, 3+4j, 5+6j])
a.real

array([1., 3., 5.])

In [56]:
#sum
np.sum([0.5, 1.5])

2.0

In [59]:
#cross
x= [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [60]:
#dot
np.dot(3, 4)

12

In [61]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [62]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [63]:
#outer
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [64]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a, b)

(70-8j)

In [65]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
np.vdot(a, b)

30

In [70]:
#random seed
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [68]:
#getfromtext
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [69]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [66]:
#get score
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [67]:
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])